[project]
name = 'VotingMachine'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.governance-token]
path = 'contracts/governance-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.membership-token]
path = 'contracts/membership-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.proposal-execution]
path = 'contracts/proposal-execution.clar'
clarity_version = 2
epoch = 2.5

[contracts.proposal-voting]
path = 'contracts/proposal-voting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
